# Generated by Django 4.2 on 2025-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived roles are hidden from user assignment'),
        ),
    ]
