# Generated by Django 4.2 on 2025-08-09 17:06

from django.db import migrations

def fix_default_roles(apps, schema_editor):
    """
    Fix existing default roles:
    - Only admin should be is_default=True (protected)
    - Dentist and staff should be is_default=False (editable)
    """
    Role = apps.get_model('users', 'Role')
    
    # Update dentist and staff roles to be editable
    Role.objects.filter(name__in=['dentist', 'staff']).update(is_default=False)
    
    # Ensure admin stays protected
    Role.objects.filter(name='admin').update(is_default=True)

def reverse_fix_default_roles(apps, schema_editor):
    """Reverse the changes if needed"""
    Role = apps.get_model('users', 'Role')
    
    # Set all built-in roles back to default
    Role.objects.filter(name__in=['admin', 'dentist', 'staff']).update(is_default=True)

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_role_is_archived'),  # Replace with your actual previous migration name
    ]

    operations = [
        migrations.RunPython(fix_default_roles, reverse_fix_default_roles),
    ]