# Generated by Django 4.2 on 2025-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the service in minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_price',
            field=models.DecimalField(decimal_places=2, help_text='Maximum price for this service', max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(decimal_places=2, help_text='Minimum price for this service', max_digits=10),
        ),
    ]
