# Generated by Django 4.2 on 2025-09-03 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('dentist', 'date', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='schedule',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Buffer time after appointment for cleaning/prep'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['dentist', 'status'], name='appointment_dentist_24c705_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['dentist', 'date'], name='appointment_dentist_0a2429_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date', 'start_time'], name='appointment_date_b5e13c_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'completed'])), fields=('schedule',), name='unique_active_appointment_per_schedule'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(check=models.Q(('buffer_minutes__gte', 0)), name='schedule_non_negative_buffer'),
        ),
    ]
