# Generated by Django 4.2 on 2025-09-06 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_alter_schedule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_working', models.BooleanField(default=True)),
                ('start_time', models.TimeField(default=datetime.time(10, 0))),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('lunch_start', models.TimeField(default=datetime.time(12, 0))),
                ('lunch_end', models.TimeField(default=datetime.time(13, 0))),
                ('has_lunch_break', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dentist', 'weekday'],
            },
        ),
        migrations.AddIndex(
            model_name='dentistschedule',
            index=models.Index(fields=['dentist', 'weekday'], name='appointment_dentist_d1c6e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='dentistschedule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='dentist_schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='dentistschedule',
            constraint=models.CheckConstraint(check=models.Q(('lunch_end__gt', models.F('lunch_start'))), name='dentist_schedule_lunch_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='dentistschedule',
            unique_together={('dentist', 'weekday')},
        ),
    ]
