# Generated by Django 4.2 on 2025-09-23 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('appointments', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyslots',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_dentist',
            field=models.ForeignKey(blank=True, help_text='Dentist assigned when appointment is confirmed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Linked patient record (set after approval)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment'], name='payment_transac_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_date'], name='payment_transac_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['receipt_number'], name='payment_transac_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentitem',
            index=models.Index(fields=['payment'], name='payment_item_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentitem',
            index=models.Index(fields=['service'], name='payment_item_service_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient'], name='payment_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['next_due_date'], name='payment_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyslots',
            index=models.Index(fields=['date'], name='daily_slots_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyslots',
            constraint=models.CheckConstraint(check=models.Q(('am_slots__gte', 0)), name='daily_slots_non_negative_am'),
        ),
        migrations.AddConstraint(
            model_name='dailyslots',
            constraint=models.CheckConstraint(check=models.Q(('pm_slots__gte', 0)), name='daily_slots_non_negative_pm'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='appt_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_dentist'], name='appt_assigned_dentist_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'period'], name='appt_date_period_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['requested_at'], name='appt_requested_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['temp_email'], name='appt_temp_email_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['temp_contact_number'], name='appt_temp_contact_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('period__in', ['AM', 'PM'])), name='appointment_valid_period'),
        ),
    ]
