# Generated by Django 4.2 on 2025-09-09 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_cleanup_old_schedule_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentslot',
            name='unique_appointment_slot',
        ),
        migrations.RemoveConstraint(
            model_name='dentistschedulesettings',
            name='unique_dentist_weekday_setting',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_status_idx',
            old_name='appointment_status_8fe9d7_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_patient_idx',
            old_name='appointment_patient_94a7ef_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_dentist_idx',
            old_name='appointment_dentist_6a4db8_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_requested_idx',
            old_name='appointment_request_becfe9_idx',
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dentistschedulesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('dentist', 'date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='dentistschedulesettings',
            unique_together={('dentist', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['dentist', 'status'], name='appt_dentist_status_idx'),
        ),
    ]
