# Generated by Django

from django.db import migrations

def cleanup_empty_contact_numbers(apps, schema_editor):
    """Convert empty string contact numbers to None"""
    Patient = apps.get_model('patients', 'Patient')
    
    # Update empty strings to None
    updated_count = Patient.objects.filter(contact_number='').update(contact_number=None)
    print(f"Updated {updated_count} patients with empty contact numbers")
    
    # Also clean up emergency contact numbers
    emergency_updated_count = Patient.objects.filter(emergency_contact_phone='').update(emergency_contact_phone=None)
    print(f"Updated {emergency_updated_count} patients with empty emergency contact numbers")

def reverse_cleanup_empty_contact_numbers(apps, schema_editor):
    """Reverse operation - convert None back to empty strings"""
    Patient = apps.get_model('patients', 'Patient')
    
    # Convert None back to empty strings
    Patient.objects.filter(contact_number__isnull=True).update(contact_number='')
    Patient.objects.filter(emergency_contact_phone__isnull=True).update(emergency_contact_phone='')

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),  # Replace with your latest migration
    ]

    operations = [
        migrations.RunPython(
            cleanup_empty_contact_numbers,
            reverse_cleanup_empty_contact_numbers,
        ),
    ]